service: studynotin-backend
runtime: nodejs18
env_variables:
  MAIL_PASS: xmsjgfjyamupjzyc
  MAIL_HOST: smtp.gmail.com
  MAIL_USER: studynation001@gmail.com
  MONGODB_URL: "mongodb+srv://Niladri2003:pownan00@studynation.1vhs6jk.mongodb.net/MED360DB"
  JWT_SECRET: "niladri"
  RAZORPAY_KEY: rzp_test_ApBTUeBOWrQlC4
  RAZORPAY_SECRET: JPVzPN4zdWmvMHJA1OHxeqWG
  CLOUD_NAME: dvbnkndyc
  API_KEY: 667753236366743
  API_SECRET: O105zScLQvu8q24z8_M5bzziOMs
  FOLDER_NAME: "MED360"
